package atividadeiii;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jose
 */
public class DetalhesConsulta extends javax.swing.JFrame {

    Paciente p = new Paciente();
    
    public DetalhesConsulta(int id) {
        //Preenche o objeto p com o pedido selecionado na tabela
        p = ListaPaciente.lista.get(id);
        initComponents();
    }
    
    public DetalhesConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel1 = new javax.swing.JPanel();
        DetalhesConsulta = new javax.swing.JLabel();
        checkConsultaRealizada = new javax.swing.JCheckBox();
        txtAreaObservacao = new javax.swing.JScrollPane();
        txtAreaReceita = new javax.swing.JTextArea();
        txtReceitaObservacoes = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DetalhesConsulta.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DetalhesConsulta.setText("Detalhes da Consulta ");

        checkConsultaRealizada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkConsultaRealizada.setText("Consulta Realizada");
        checkConsultaRealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConsultaRealizadaActionPerformed(evt);
            }
        });

        txtAreaReceita.setColumns(20);
        txtAreaReceita.setRows(5);
        txtAreaReceita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAreaObservacao.setViewportView(txtAreaReceita);

        txtReceitaObservacoes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtReceitaObservacoes.setText("Receita e Observações:");

        btnSair.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addComponent(DetalhesConsulta)
                        .addGap(68, 68, 68)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkConsultaRealizada)
                    .addComponent(txtReceitaObservacoes)
                    .addComponent(txtAreaObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, Short.MAX_VALUE))
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DetalhesConsulta))
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair)))
                .addGap(29, 29, 29)
                .addComponent(checkConsultaRealizada)
                .addGap(12, 12, 12)
                .addComponent(txtReceitaObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAreaObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnFinalizar))
        );

        if(p.isConsultaRealizada()) {
            checkConsultaRealizada.setSelected(true);
            checkConsultaRealizada.setEnabled(false);
        }else{
            checkConsultaRealizada.setSelected(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
                         
        
        if(checkConsultaRealizada.isSelected()) {
            p.setConsultaRealizada(true);
            p.setReceita(txtAreaReceita.getText());
            JOptionPane.showMessageDialog(null, "Consulta finalizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Consulta ainda não foi realizada!");
        }

        atualizarTelaPrincipal();

        dispose(); // Fechar a janela de Detalhes da Consulta
    }

    private void atualizarTelaPrincipal() {
        // Adicione lógica para atualizar a Tela Principal após finalizar a consulta
        // Isso pode envolver a recarga da lista de consultas na Tela Principal
        TelaPrincipal tp = new TelaPrincipal();
        tp.setLocationRelativeTo(null);
        tp.setVisible(true);
    
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void checkConsultaRealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConsultaRealizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkConsultaRealizadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetalhesConsulta;
    private javax.swing.JPanel Painel1;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox checkConsultaRealizada;
    private javax.swing.JScrollPane txtAreaObservacao;
    private javax.swing.JTextArea txtAreaReceita;
    private javax.swing.JLabel txtReceitaObservacoes;
    // End of variables declaration//GEN-END:variables
}
