
package guibuilder;

import javax.swing.JOptionPane;


public class CadastrarPedido extends javax.swing.JFrame {

    public CadastrarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Acompanhamento = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        txtBemVindos = new javax.swing.JLabel();
        txtSelecione = new javax.swing.JLabel();
        btnSair = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        txtAcompanhamento = new javax.swing.JLabel();
        txtAdicional = new javax.swing.JLabel();
        fieldPreco = new javax.swing.JTextField();
        fieldQuantidade = new javax.swing.JTextField();
        fieldNomeCliente = new javax.swing.JTextField();
        rdnSim = new javax.swing.JRadioButton();
        rdnNao = new javax.swing.JRadioButton();
        btnCadastrar = new javax.swing.JButton();
        comboAdicional = new javax.swing.JComboBox<>();
        txtNomeCliente = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        feedBackInformacoes = new javax.swing.JLabel();
        feedBackNome = new javax.swing.JLabel();
        feedBackPreco = new javax.swing.JLabel();
        feedBackQuantidade = new javax.swing.JLabel();
        feedBackAdicional = new javax.swing.JLabel();
        feedBackAcompanhamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBemVindos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtBemVindos.setText("Casdatro de Pedidos");
        txtBemVindos.setRequestFocusEnabled(false);

        txtSelecione.setText("Selecione uma das opções abaixo:");

        btnSair.setLabel("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(txtSelecione)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(txtBemVindos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtBemVindos))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtSelecione)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txtAcompanhamento.setText("Acompanhamento:");

        txtAdicional.setText("Adicional ");

        fieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeClienteActionPerformed(evt);
            }
        });

        Acompanhamento.add(rdnSim);
        rdnSim.setText("Sim");
        rdnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnSimActionPerformed(evt);
            }
        });

        Acompanhamento.add(rdnNao);
        rdnNao.setText("Não ");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        comboAdicional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção:", "Não", "Bacon", "Celoba", "Calabresa", "Bife extra \t", "Catupiry", "4 Queijos ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdnSim)
                        .addGap(18, 18, 18)
                        .addComponent(rdnNao))
                    .addComponent(txtAcompanhamento))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdicional)
                            .addComponent(comboAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAcompanhamento)
                    .addComponent(txtAdicional))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnSim)
                    .addComponent(rdnNao)
                    .addComponent(comboAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtNomeCliente.setText("Nome do Cliente:");

        txtPreco.setText("Preço R$:");

        txtQuantidade.setText("Quantidade:");

        feedBackInformacoes.setText("Informações do pedido:");

        feedBackNome.setText("Nome Cliente: ");

        feedBackPreco.setText("Preço:");

        feedBackQuantidade.setText("Quantidade:");

        feedBackAdicional.setText("Adicional:");

        feedBackAcompanhamento.setText("Acompanhamento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedBackInformacoes)
                    .addComponent(feedBackNome)
                    .addComponent(feedBackPreco)
                    .addComponent(feedBackQuantidade)
                    .addComponent(feedBackAdicional)
                    .addComponent(feedBackAcompanhamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(feedBackInformacoes)
                .addGap(18, 18, 18)
                .addComponent(feedBackNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedBackPreco)
                .addGap(18, 18, 18)
                .addComponent(feedBackQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(feedBackAcompanhamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedBackAdicional)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNomeCliente)
                        .addGap(79, 79, 79)
                        .addComponent(txtPreco)
                        .addGap(98, 98, 98)
                        .addComponent(txtQuantidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente)
                    .addComponent(txtPreco)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void rdnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnSimActionPerformed

    private void fieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeClienteActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Pedido p = new Pedido();
        p.setNomeCliente(fieldNomeCliente.getText());
        
        p.setPreco(Double.parseDouble(fieldPreco.getText()));
        
        p.setQuantidade(Integer.parseInt(fieldQuantidade.getText()));
        
        if(rdnSim.isSelected()){
            p.setAcompanhamento("Sim");
        }else if (rdnNao.isSelected()){
            p.setAcompanhamento("Não");
        }else {
            p.setAcompanhamento("");
        }
        
        p.setAdicional(comboAdicional.getSelectedItem().toString());
       
        JOptionPane.showMessageDialog(null,"Pedido cadastrado com Sucesso!");
        
        feedBackNome.setText("Nome do Cliente: " + p.getNomeCliente());
        feedBackPreco.setText("Preço: " + p.getPreco());
        feedBackQuantidade.setText("Quantidade: " + p.getQuantidade());
        feedBackAcompanhamento.setText("Acompanhamento? " + p.getAcompanhamento());
        feedBackAdicional.setText("Adicional? " + p.getAdicional());
    }//GEN-LAST:event_btnCadastrarActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Acompanhamento;
    private javax.swing.JButton btnCadastrar;
    private java.awt.Button btnSair;
    private javax.swing.JComboBox<String> comboAdicional;
    private javax.swing.JLabel feedBackAcompanhamento;
    private javax.swing.JLabel feedBackAdicional;
    private javax.swing.JLabel feedBackInformacoes;
    private javax.swing.JLabel feedBackNome;
    private javax.swing.JLabel feedBackPreco;
    private javax.swing.JLabel feedBackQuantidade;
    private javax.swing.JTextField fieldNomeCliente;
    private javax.swing.JTextField fieldPreco;
    private javax.swing.JTextField fieldQuantidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painel1;
    private javax.swing.JRadioButton rdnNao;
    private javax.swing.JRadioButton rdnSim;
    private javax.swing.JLabel txtAcompanhamento;
    private javax.swing.JLabel txtAdicional;
    private javax.swing.JLabel txtBemVindos;
    private javax.swing.JLabel txtNomeCliente;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtSelecione;
    // End of variables declaration//GEN-END:variables
}
