/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividadeiv;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    public void geraAcessbilidade() {
           
            btnSalvar.setMnemonic(KeyEvent.VK_D);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        txtMedidorPressao = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtData = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        txtPressaoAlta = new javax.swing.JLabel();
        txtPressaoBaixa = new javax.swing.JLabel();
        fieldData = new javax.swing.JTextField();
        fieldPressaoAlta = new javax.swing.JTextField();
        fieldHora = new javax.swing.JTextField();
        fieldPressaoBaixa = new javax.swing.JTextField();
        txtInformações = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMedidorPressao.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtMedidorPressao.setText("Medidor de Pressão");
        txtMedidorPressao.setToolTipText("Medidor de Pressão ");
        txtMedidorPressao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSalvar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar as informações digitadas");
        btnSalvar.setNextFocusableComponent(fieldData);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtData.setText("Data:");
        txtData.setToolTipText("Digite a data no campo abaixo");

        txtHora.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtHora.setText("Hora:");
        txtHora.setToolTipText("Digite a hora no campo abaixo");

        txtPressaoAlta.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtPressaoAlta.setText("Pressão Sistólica:");
        txtPressaoAlta.setToolTipText("Digite a Pressão Sistólica abaixo");

        txtPressaoBaixa.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtPressaoBaixa.setText("Pressão Diastólica");
        txtPressaoBaixa.setToolTipText("Digite a Pressão Diastólica abaixo");

        fieldData.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        fieldData.setToolTipText("informe a data com dia, mês e ano");
        fieldData.setNextFocusableComponent(fieldHora);

        fieldPressaoAlta.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        fieldPressaoAlta.setToolTipText("Insira a Pressão Sistólica");
        fieldPressaoAlta.setNextFocusableComponent(txtPressaoBaixa);

        fieldHora.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        fieldHora.setToolTipText("Insira a Hora");
        fieldHora.setNextFocusableComponent(fieldPressaoAlta);

        fieldPressaoBaixa.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        fieldPressaoBaixa.setToolTipText("Insira a Pressão Diastólica");
        fieldPressaoBaixa.setNextFocusableComponent(btnSalvar);

        txtInformações.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtInformações.setText("Por favor insira as informações a seguir:");
        txtInformações.setToolTipText("Inserir as informações a seguir:");

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtData)
                                        .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPressaoAlta))
                                    .addGroup(PainelLayout.createSequentialGroup()
                                        .addComponent(fieldPressaoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGap(205, 205, 205)
                                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHora)
                                    .addComponent(txtPressaoBaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldPressaoBaixa)
                                    .addComponent(fieldHora)))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtInformações))))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(txtMedidorPressao))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnSalvar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtMedidorPressao)
                .addGap(18, 18, 18)
                .addComponent(txtInformações)
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData)
                    .addComponent(txtHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPressaoAlta)
                    .addComponent(txtPressaoBaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPressaoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPressaoBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtMedidorPressao.getAccessibleContext().setAccessibleDescription("Medidor de Pressão");
        fieldData.getAccessibleContext().setAccessibleName("Data");
        fieldPressaoAlta.getAccessibleContext().setAccessibleName("Pressão Sistólica");
        fieldHora.getAccessibleContext().setAccessibleName("Hora");
        fieldPressaoBaixa.getAccessibleContext().setAccessibleName("Pressão Diastólica");
        txtInformações.getAccessibleContext().setAccessibleDescription("Por favor insira as informações a seguir:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Paciente p = new Paciente();
        try {
            p.setData(fieldData.getText());
            p.setHora(fieldHora.getText());
            p.setPressaoAlta(Integer.parseInt(fieldPressaoAlta.getText()));
            p.setPressaoBaixa(Integer.parseInt(fieldPressaoBaixa.getText()));
            
            if(PacienteCSV.AdicionarPaciente(p)) {
                JOptionPane.showMessageDialog(null, "Informações cadastradas com Sucesso!\n Os dados cadastrados são:\nData: " +
                        p.getData() + "\n" + "Hora: " + p.getHora() + "\n" + 
                        "Pressão Sistólica: " + p.getPressaoAlta() + "\n" + "Pressão Diastólica: " + p.getPressaoBaixa() + "\n");
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "As informações não poderam ser cadastradas");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField fieldData;
    private javax.swing.JTextField fieldHora;
    private javax.swing.JTextField fieldPressaoAlta;
    private javax.swing.JTextField fieldPressaoBaixa;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtInformações;
    private javax.swing.JLabel txtMedidorPressao;
    private javax.swing.JLabel txtPressaoAlta;
    private javax.swing.JLabel txtPressaoBaixa;
    // End of variables declaration//GEN-END:variables
}
